language: php
php:
#  - 5.6
  - 7.0.13
  - 7.1
before_install:
 - cd ../..
 - git clone https://github.com/magento/marketplace-eqp magento-coding-standard # install magento code standard QA tool
 - cd magento-coding-standard
 - composer install
 - cd ..

script:
 - magento-coding-standard/vendor/bin/phpcs $TRAVIS_BUILD_DIR --standard=MEQP2 --severity=10 --extensions=php,phtml # check module code quality
