language: php
php:
#  - 5.6
  - 7.0.13
  - 7.1
services:
  - mysql
env:
  - MAGENTO_VERSION=2.2.4
#  - MAGENTO_VERSION=2.1.12
before_install:
 - mysql -e 'CREATE DATABASE magento;' # create database
 - cd ../..
 - git clone https://github.com/magento/marketplace-eqp magento-coding-standard # install magento code standard QA tool
 - cd magento-coding-standard
 - composer install
 - cd ..
 - git clone https://github.com/magento/magento2 # install Magento2 from the Github
 - cd magento2
 - composer install --prefer-dist
 - git checkout tags/$MAGENTO_VERSION # take specific Magento version
 - cd ..
 - ./magento2/bin/magento setup:install --db-host=localhost --db-prefix=tnw --db-name=magento --db-user=root --backend-frontname=admin --base-url=http://magento-qa.box/ --language=en_US --timezone=America/Chicago --currency=USD --admin-lastname=Admin --admin-firstname=Admin --admin-email=admin@example.com --admin-user=admin --admin-password=admin123 --cleanup-database --use-rewrites=1
 - ./magento2/bin/magento --version # check
 - composer require tnw/soap-client=1.0.8
 - ./magento2/bin/magento setup:upgrade
 - ./magento2/bin/magento setup:di:compile
 

script:
 - mkdir -p magento2/app/code # link our module to the Magento2 folder to check installation process
 - ln -s $TRAVIS_BUILD_DIR magento2/app/code/TNW
 - rm -rf ./magento2/generated/*
 - ./magento2/bin/magento module:status
 - ./magento2/bin/magento module:enable TNW_Stripe
 - ./magento2/bin/magento setup:upgrade
 - ./magento2/bin/magento setup:di:compile
 - magento-coding-standard/vendor/bin/phpcs $TRAVIS_BUILD_DIR --standard=MEQP2 --severity=10 --extensions=php,phtml # check module code quality
