sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  hosts:
      - magento2.travis
language: php
php:
  - 7.1
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
  matrix:
    - TEST_SUITE=unit
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
before_script: ./.travis/before_script.sh
script: phpunit -c magento2/dev/tests/$TEST_SUITE
