version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache
    working_directory: ~/tnw_extension
    steps:
      - run:
          name: Install Git
          command: |
            sudo apt-get update
            sudo apt-get install -y git
      - run:
          name: Permissions
          command: |
            cd /var/www/
            sudo chown -R circleci:circleci html
      - checkout
      - run:
          name: Get Magento Code Quality Tool
          command: |
            cd /var/www/html/
            git clone https://github.com/magento/marketplace-eqp magento-coding-standard
            cd magento-coding-standard
            composer install
      - run:
          name: Installing Magento
          command: |
            cd /var/www/html/
            git clone https://github.com/magento/magento2
            cd magento2
            composer install --prefer-dist
            git checkout tags/2.2.4
            ./bin/magento --version
            
      #- run:
      #    name: Create the Folder for the Extension
      #    command: |
      #      cd /var/www/html/app
      #      mkdir code
      #      cd code
      #      mkdir TNW
      #      cd TNW
      #      mkdir Stripe           
      #- run:
      #    name: Copy the Extension Files
      #    command: |
      #      cp -R ~/tnw_extension/* /var/www/html/app/code/TNW/Stripe/
      #- run:
      #    name: Install the Extension
      #    command: |
      #      cd /var/www/html
      #      php bin/magento setup:upgrade
      #- run:
      #    name: Compile the Code
      #    command: |
      #      cd /var/www/html
      #      php bin/magento setup:di:compile 
      - run:
          name: TEST
          command: |
            cd ~
            ls -al
           
      #- run:
      #    name: Install dependencies
      #    command: |
      #      cd ~/cko_magento2/tests && npm i 
      #- run:
      #    name: Run Tests
      #    command: |
      #      cd ~/cko_magento2/tests && ./node_modules/.bin/chimp config/chimp.js --fail-fast
      #- store_artifacts:
      #    path: ~/cko_magento2/tests/screenshots
      #    destination: Failed-Tests
