version: 2

jobs:
  build:
    docker:
      - image: integrationcheckout/ecommerce:magento2.2
    working_directory: ~/tnw_extension
    steps:
      - checkout
      - run:
          name: Prepare & Restart Apache + MySQL
          command: |
            sudo a2enmod rewrite && sudo service apache2 restart && sudo service mysql restart
      - run:
          name: Get Magento Code Quality Tool
          command: |
            cd /var/www/html/
            git clone https://github.com/magento/marketplace-eqp magento-coding-standard
            cd magento-coding-standard
            composer install
      - run:
          name: Create the Folder for the Extension
          command: |
            cd /var/www/html/magento22/app
            sudo mkdir code
            cd code
            sudo mkdir TNW
            cd TNW
            sudo mkdir Stripe           
      - run:
          name: Copy the Extension Files
          command: |
            sudo cp -R ~/tnw_extension/* /var/www/html/magento22/app/code/TNW/Stripe/
      - run:
          name: Install the Extension
          command: |
            cd /var/www/html/magento22
            sudo php bin/magento setup:upgrade
      - run:
          name: Compile the Code
          command: |
            cd /var/www/html/magento22
            sudo php bin/magento setup:di:compile      
      #- run:
      #    name: Install dependencies
      #    command: |
      #      cd ~/cko_magento2/tests && npm i 
      #- run:
      #    name: Run Tests
      #    command: |
      #      cd ~/cko_magento2/tests && ./node_modules/.bin/chimp config/chimp.js --fail-fast
      #- store_artifacts:
      #    path: ~/cko_magento2/tests/screenshots
      #    destination: Failed-Tests
