version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_PASSWORD: mage
          MYSQL_USER: mage
          MYSQL_DATABASE: magento
          MYSQL_ROOT_PASSWORD: docker
    working_directory: ~/tnw_extension
    steps:
      - checkout
      - run:
          name: Update System Package
          command: |
            sudo apt-get update
      - run:
          name: Install System Package
          command: |
            sudo apt install -y libicu-dev libxml2-dev libxslt1-dev zlib1g-dev libmcrypt-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev
      - run:
          name: Configure PHP ext
          command: |
            sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - run:
          name: Install PHP ext
          command: |
            sudo docker-php-ext-install -j$(nproc) intl soap xsl zip mcrypt pdo pdo_mysql gd gettext mbstring bcmath
      - run:
          name: Permissions
          command: |
            cd /var/www/
            sudo chown -R circleci:circleci html
      - run:
          name: Get Magento Code Quality Tool
          command: |
            cd /var/www/html/
            git clone https://github.com/magento/marketplace-eqp magento-coding-standard
            cd magento-coding-standard
            composer install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Installing Magento
          command: |
            cd /var/www/html/
            wget https://github.com/magento/magento2/archive/2.2.4.tar.gz -O - | tar -xz
            cd magento2-2.2.4
            composer install --prefer-dist
            ./bin/magento setup:install --backend-frontname admin --db-host localhost --db-prefix tnw --db-name magento --db-user mage --db-password mage --base-url http://magento-qa.box/ --language en_US --timezone America/Chicago --currency USD --admin-lastname Admin --admin-firstname Admin --admin-email admin@example.com --admin-user admin --admin-password admin123 --cleanup-database --use-rewrites 1
            ./bin/magento --version
      - run:
          name: Create the Folder for the Extension
          command: |
            cd /var/www/html/magento2-2.2.4/app
            mkdir -p code/TNW/Stripe
      - run:
          name: Copy the Extension Files
          command: |
            ln -s $CIRCLE_WORKING_DIRECTORY /var/www/html/magento2-2.2.4/app/code/TNW/Stripe/
      - run:
          name: Install the Extension
          command: |
            cd /var/www/html/magento2-2.2.4
            rm -rf ./generated/*
            ./bin/magento module:status
            ./bin/magento module:enable TNW_Subscriptions
            ./bin/magento setup:upgrade
      - run:
          name: Compile the Code
          command: |
            cd /var/www/html/magento2-2.2.4
            php bin/magento setup:di:compile
      - run:
          name: Run Magento Coding Standard
          command: |
            cd /var/www/html
            ./magento-coding-standard/vendor/bin/phpcs $CIRCLE_WORKING_DIRECTORY --standard=MEQP2 --severity=10 --extensions=php,phtml
      - run:
          name: Run Unit Test
          command: |
            cd /var/www/html/magento2-2.2.4
            ./bin/magento dev:tests:run -c'--filter=TNW' unit
